version: '3.4'

services:
  redis:
    container_name: currency_checker_redis
    image: redis:6
    env_file:
      - conf/.env
    ports:
      - 6379:6379
  postgres:
    container_name: currency_checker_postgres
    image: postgres:14
    ports:
      - 5432:5432
    env_file:
      - conf/.env
    environment:
      POSTGRES_USER: ${POSTGRES__USER:-currency_checker}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD:-currency_checker}
      POSTGRES_DB: ${POSTGRES__DATABASE:-currency_checker}
  api:
    container_name: currency_checker_api
    build: .
    env_file:
      - conf/.env
    volumes:
      - ./currency_checker:/app/currency_checker
    ports:
      - 8000:8000
    environment:
      RUN_MIGRATIONS_ON_STARTUP: 1
    command: ["poetry", "run", "uvicorn", "currency_checker.api.__main__:app", "--host", "", "--port=8000"]
    # For better performance on local machine
#    command: ["poetry", "run", "gunicorn", "currency_checker.api.__main__:app", "--workers", "8", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "[::]:8000"]
  scheduler:
    container_name: currency_checker_scheduler
    build: .
    env_file:
      - conf/.env
    volumes:
      - ./currency_checker:/app/currency_checker
    command: ["poetry", "run", "python3", "-m", "currency_checker.scheduler"]
  broker:
    container_name: currency_checker_broker
    build: .
    env_file:
      - conf/.env
    volumes:
      - ./currency_checker:/app/currency_checker
    command: ["poetry", "run", "python3", "-m", "currency_checker.scheduler.broker"]
