#!/bin/sh

set -e

if [ "$RUN_MIGRATIONS_ON_STARTUP" = 1 ]
then
    >&2 echo "Applying migrations..."
    cd currency_checker/infrastructure/migrations
    poetry run alembic upgrade head
fi

exec "$@"
