name: Checks
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v4
    - uses: danfimov/setup-poetry@v1
      with:
        python-version: '3.11'
        install-args: '--no-root --all-extras'
    - run: make lint
