name: Checks
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install --upgrade pip
    - run: make install
    - run: make lint
